# Generated by Django 2.1.7 on 2019-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proexper',
            name='main_work',
            field=models.TextField(default=''),
        ),
    ]
