# Generated by Django 2.1.7 on 2019-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0002_proexper_main_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexper',
            name='name',
        ),
        migrations.AddField(
            model_name='workexper',
            name='honor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workexper',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workexper',
            name='salary',
            field=models.CharField(default='', max_length=50),
        ),
    ]
