# Generated by Django 2.1.7 on 2019-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0003_auto_20190428_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexper',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
