# Generated by Django 2.1.7 on 2019-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0004_workexper_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='badsicinfo',
            name='want_position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='badsicinfo',
            name='want_salary',
            field=models.CharField(default='', max_length=50),
        ),
    ]
