# Generated by Django 2.1.7 on 2019-05-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0006_auto_20190428_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='jianli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('jianli', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
