# Generated by Django 2.1.7 on 2019-04-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('idName', models.CharField(max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
                ('position_type', models.CharField(max_length=50)),
                ('position_trade', models.CharField(max_length=50)),
            ],
        ),
    ]
