# Generated by Django 2.1.7 on 2019-04-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobinfoClik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('salary', models.CharField(default='', max_length=255)),
                ('companyName', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
                ('idName', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('info', models.TextField(default='')),
                ('clik', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
