# Generated by Django 2.1.7 on 2019-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190501_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='welfare',
        ),
        migrations.RemoveField(
            model_name='jobinfoclik',
            name='welfare',
        ),
    ]
