# Generated by Django 2.1.7 on 2019-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190502_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='clik',
            field=models.IntegerField(default=0),
        ),
    ]
