# Generated by Django 2.1.7 on 2019-05-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_jobinfo_clik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobinfoClik',
        ),
    ]
