# Generated by Django 2.1.7 on 2019-05-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_delete_jobinfoclik'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
