# Generated by Django 2.1.7 on 2019-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_jobinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='companyEmail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
